excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://dfrnks.github.io
title: MPBrain
email: douglasfrancardoso@gmail.com
author: dfrnks
description: My personal brain
paginate: 10
google_analytics: UA-84126815-1